Student.create(name: "Emmanuel", email: "emmanuel@gmail.com", course: "Software Engineering")
Student.create(name: "Meshack", email: "meshack@gmail.com", course: "Software Engineering")
Student.create(name: "Marcel", email: "marcel@gmail.com", course: "Software Engineering")
Student.create(name: "Deno", email: "deno@gmail.com", course: "Software Engineering")
Student.create(name: "Brian", email: "brian@gmail.com", course: "Software Engineering")